# Generated by Django 6.0.1 on 2026-05-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masters', '0001_initial'),
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countersaleitem',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin'),
        ),
        migrations.AlterField(
            model_name='sparesissuealterationdeleted',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin'),
        ),
        migrations.AlterField(
            model_name='sparesissuealterationitem',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin'),
        ),
        migrations.RemoveField(
            model_name='rack',
            name='warehouse',
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack'),
        ),
        migrations.AlterField(
            model_name='countersaleitem',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack'),
        ),
        migrations.AlterField(
            model_name='sparesissuealterationitem',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack'),
        ),
        migrations.AlterField(
            model_name='sparesissuealterationdeleted',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.rack'),
        ),
        migrations.AlterField(
            model_name='sparesitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.sparescategory'),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='supplierquote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.supplier'),
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='parent_warehouse',
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse'),
        ),
        migrations.AlterField(
            model_name='sparesissuealteration',
            name='godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse'),
        ),
        migrations.AlterField(
            model_name='countersale',
            name='godown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='masters.warehouse'),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.warehouse'),
        ),
        migrations.AlterModelOptions(
            name='countersale',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='countersalereturn',
            options={'ordering': ['-return_date']},
        ),
        migrations.AlterModelOptions(
            name='purchaseinvoice',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='sparesissuealteration',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='supplierquote',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='sparesitem',
            old_name='hsn_code',
            new_name='hsn_sac',
        ),
        migrations.RenameField(
            model_name='sparesitem',
            old_name='purchase_rate',
            new_name='standard_selling_rate',
        ),
        migrations.RenameField(
            model_name='sparesitem',
            old_name='selling_rate',
            new_name='valuation_rate',
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='allow_negative_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='is_ineligible_for_itc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='item_sub_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='maintain_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='max_discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='opening_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='part_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='reorder_qty',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='sparesitem',
            name='warranty_period_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='countersaleitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='countersalereturnitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='mode_of_transport',
            field=models.CharField(blank=True, choices=[('road', 'Road'), ('rail', 'Rail'), ('air', 'Air'), ('ship', 'Ship')], default='road', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sparesissuealterationitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='supplierquoteitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='ItemRackBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='masters.bin')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rack_bins', to='spares.sparesitem')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.rack')),
            ],
        ),
        migrations.DeleteModel(
            name='Bin',
        ),
        migrations.DeleteModel(
            name='Rack',
        ),
        migrations.DeleteModel(
            name='SparesCategory',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
